[versions]
agp = "8.13.1"
androidxComposeUiUiTextGoogleFonts16 = "1.6.0"
androidxCredentialsCredentialsPlayServicesAuth14 = "1.3.0"
androidxCredentialsVersion = "1.3.0"
androidxNavigationNavigationCompose10 = "2.7.3"
androidxRoomRoomKtx6 = "2.8.4"
androidxRoomRoomRuntime13 = "2.8.4"
androidxWorkWorkRuntimeKtx4 = "2.9.0"
comAndroidToolsDesugar_jdk_libs5 = "2.1.5"
comGoogleAndroidGmsPlayServicesAuth15 = "21.0.0"
comGoogleAndroidLibrariesIdentityGoogleidGoogleid = "1.1.1"
comSquareupOkhttp3LoggingInterceptor7 = "4.11.0"
comSquareupRetrofit2ConverterGson8 = "2.9.0"
comSquareupRetrofit2Retrofit9 = "2.9.0"
generativeaiVersion = "0.1.2"
googleAccompanistPermissions = "0.32.0"
ioCoilKtCoilCompose11 = "2.5.0"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.0"
composeBom = "2024.09.00"
orgJetbrainsKotlinxKotlinxCoroutinesPlayServices2 = "1.7.3"
orgJetbrainsKotlinxKotlinxSerializationJson3 = "1.6.0"
pytorch_android = "1.13.1"
pytorch_android_torchvisionVersion = "1.13.1"

[libraries]
androidx-compose-material-material-icons-extended13 = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-ui-ui-text-google-fonts17 = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "androidxComposeUiUiTextGoogleFonts16" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-credentials-credentials-play-services-auth28 = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "androidxCredentialsCredentialsPlayServicesAuth14" }
androidx-credentials-credentials2 = { module = "androidx.credentials:credentials", version.ref = "androidxCredentialsVersion" }
androidx-navigation-navigation-compose12 = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigationNavigationCompose10" }
androidx-room-room-ktx8 = { module = "androidx.room:room-ktx", version.ref = "androidxRoomRoomKtx6" }
androidx-room-room-runtime21 = { module = "androidx.room:room-runtime", version.ref = "androidxRoomRoomRuntime13" }
androidx-work-work-runtime-ktx6 = { module = "androidx.work:work-runtime-ktx", version.ref = "androidxWorkWorkRuntimeKtx4" }
com-android-tools-desugar_jdk_libs6 = { module = "com.android.tools:desugar_jdk_libs", version.ref = "comAndroidToolsDesugar_jdk_libs5" }
com-google-accompanist-accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "googleAccompanistPermissions" }
com-google-android-gms-play-services-auth16 = { module = "com.google.android.gms:play-services-auth", version.ref = "comGoogleAndroidGmsPlayServicesAuth15" }
com-google-android-libraries-identity-googleid-googleid3 = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "comGoogleAndroidLibrariesIdentityGoogleidGoogleid" }
com-squareup-okhttp3-logging-interceptor8 = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "comSquareupOkhttp3LoggingInterceptor7" }
com-squareup-retrofit2-converter-gson9 = { module = "com.squareup.retrofit2:converter-gson", version.ref = "comSquareupRetrofit2ConverterGson8" }
com-squareup-retrofit2-retrofit10 = { module = "com.squareup.retrofit2:retrofit", version.ref = "comSquareupRetrofit2Retrofit9" }
google-generativeai = { module = "com.google.ai.client.generativeai:generativeai", version.ref = "generativeaiVersion" }
io-coil-kt-coil-compose13 = { module = "io.coil-kt:coil-compose", version.ref = "ioCoilKtCoilCompose11" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
org-jetbrains-kotlinx-kotlinx-coroutines-play-services4 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "orgJetbrainsKotlinxKotlinxCoroutinesPlayServices2" }
org-jetbrains-kotlinx-kotlinx-serialization-json5 = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "orgJetbrainsKotlinxKotlinxSerializationJson3" }
pytorch-pytorch_android_torchvision = { module = "org.pytorch:pytorch_android_torchvision", version.ref = "pytorch_android_torchvisionVersion" }
pytorch_android = { module = "org.pytorch:pytorch_android", version.ref = "pytorch_android" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

